Allow static build of lib-express to simplify application deployment
linkineo/express-cpp pull request #1
Opened 2017-05-28 11:57 UTC by daminetreg

Hey @linkineo and how is the weekend ? :smile:

I just made some change to the build files for the purpose of deploying more easily application built on top of express : 
  - allow static build.
  - avoid compilation of unit test.

See you soon

2017-05-28 21:39 UTC, linkineo requested changes
Hello Damien,

Thanks for your contribution. I added a few comments and change requests.

See you
Patrick

2017-05-28 21:39 UTC, linkineo commented on CMakeLists.txt
> -add_definitions(--std=c++11)
Why do you remove the C++11 flag ? When doing so, it still compiles on travis as I'm using new compilers with this setting as default, but on OS X this is not default yet and fails, so I need it.

2017-05-28 21:39 UTC, linkineo commented on CMakeLists.txt
> +find_package(Boost 1.59 REQUIRED COMPONENTS regex coroutine context thread filesystem system date_time)
I just tested again, SimpleWebServer as integrated in express no longer needs coroutine or context. It compiles without them for sure: 
`c++   -dynamiclib -Wl,-headerpad_max_install_names -current_version 0.1.0 -o libexpress-cpp.0.1.0.dylib -install_name /Users/linkineo/Devl/tests/express-cpp/build/libexpress-cpp.0.1.0.dylib CMakeFiles/express-cpp.dir/src/application/application.cpp.o CMakeFiles/express-cpp.dir/src/request/request.cpp.o CMakeFiles/express-cpp.dir/src/response/response.cpp.o /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_date_time-mt.a`

2017-05-28 21:39 UTC, linkineo commented on CMakeLists.txt
> -add_library(express-cpp SHARED ${EXPRESS_SRC})
Well, I'm ok for static build support as an OPTION, but not as a default, which you instated by doing this. It's ok for the user to say something like -DBUILD_SHARED_LIBS=OFF, but when not specifying any option, it has to be a shared library.

2017-05-28 21:39 UTC, linkineo commented on CMakeLists.txt
> +  SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
It this portable ?

2017-05-29 07:40 UTC, daminetreg commented on CMakeLists.txt
> +  SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
Oh yes I forgot to add if (linux). Good catch.

2017-05-29 07:41 UTC, daminetreg commented on CMakeLists.txt
> +find_package(Boost 1.59 REQUIRED COMPONENTS regex coroutine context thread filesystem system date_time)
ok good then we can remove them.

2017-05-29 07:42 UTC, daminetreg commented on CMakeLists.txt
> -add_definitions(--std=c++11)
Yes I wanted to replace with CXX_STANDARD.

2017-05-29 07:49 UTC, daminetreg commented on CMakeLists.txt
> -add_library(express-cpp SHARED ${EXPRESS_SRC})
Why not static by default, it's actually the praised way by CMake and massive projects like hunter. It in fact makes application deployment way easier I think.

But I add it per default ON in your project, even though I think it should be OFF per default.

2017-05-29 08:39 UTC, linkineo commented
Great, thanks !

2017-05-29 08:39 UTC, merged

2017-05-29 08:59 UTC, daminetreg commented
Thanks for merging 😊

--
Damien Buhl
Software Developer

> On 29 May 2017, at 10:39, Patrick Wieder <notifications@github.com> wrote:
> 
> Merged #1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>